m13253/dns-over-https

Readme.md

Golang 1.9 is required since the dial field in client.go:87 has been added in golang 1.9

Updated required golang version to 1.9

---

doh-client/client.go
doh-client/config.go
doh-client/doh-client.conf
doh-server/config.go
doh-server/doh-server.conf
doh-server/server.go

This PR adds support for multiple listen addresses, like other similar software allows to (dnsmasq, stubby, dnscrypt-proxy etc).
The only downside I can see is that it breaks the configuration for those who have it already installed.

Add client/server support for multiple listen addresses

---

doh-server/google.go

Allow the "cd" parameter to be case insensitive to work with some clients that send True/False instead of true/false such as gDNS.

doh-server: change to google.go

---

doh-server/config.go
doh-server/doh-server.conf
doh-server/ietf.go

pull again, with better compatible for apache/nginx log default format

log real client ip behind a HTTPS gateway

---

doh-server/config.go
doh-server/doh-server.conf
doh-server/main.go
doh-server/server.go

This commit adds a `local_addr` string value to `doh-server.conf`, specifying the IP address and port from which outgoing calls to upstream DNS resolvers should originate. This value is set as the `udpClient`'s and `tcpClient`'s `Dialer.LocalAddr` when initializing a `NewServer`. If the value is left empty in `doh-server.conf`, it defaults to the first `listen` address (which in turn defaults to `"127.0.0.1:8053"`).
One use case for this would be if `doh-server` is proxying requests to a local DNS resolver (e.g. `unbound` or Pi-hole). Up to version 2.0.0, all DNS queries from `doh-server` are sent from `127.0.0.1` (even if the `listen` address is set to a different loopback IP address), making it hard to distinguish them from all other local DNS queries from the same machine in the query …

Add local_addr configuration for doh-server

---

darwin-wrapper/Makefile

This should fix macos build errors between swift 5 and older versions.

Make Makefile compatible with swift5 and older swift versions

---

doh-client/doh-client.conf

The new ietf endpoint is the only one in the documentation now:
https://developers.google.com/speed/public-dns/docs/doh/
Their blog post prefers the new address too:
https://security.googleblog.com/2019/06/google-public-dns-over-https-doh.html

Update address for google's resolver

---

doh-client/ietf.go
doh-server/config.go
doh-server/doh-server.conf
doh-server/ietf.go
doh-server/server.go
json-dns/unmarshal.go

~~This PR adds support for DNS-over-TLS (DoT) upstream resolvers.~~
~~It adds a new configuration option which affects declared resolvers globally:~~
```
tls_only = false
```
A different approach, more invasive but which gives more flexibility, would be to get away from the global type booleans and instead support configuration declarations like:
```
upstream = [
"tcp:1.1.1.1:53",
"tcp-tls:1.0.0.1:853",
"udp:8.8.8.8:53",
]
```
Let me know if you prefer the latter instead, I could rewrite this patch.
Edit: rewritten the patch to use above approach.

Add support for DNS-over-TLS upstream resolvers

---

doh-server/server.go

If the client have `no_ecs=true` in the query string, then ECS is disabled on-the-fly for this client.

Allow client opt-out of EDNS0 Client Subnet

---

Readme.md

doc: document upstream_selector

---

Readme.md

I would like to add an example for docker based doh-server setup. I had been using this setup since last 5 months and I believe this will make things easier for people who wants to use docker for setting up DoH server. Please let me know if I need to add more information or correct any information in documentation.

Added example configuration for Docker Flow Proxy + Docker

---

Dockerfile.client
Readme.md

Proposed enhancement to Readme.md. Pi Hole can also provide DNSSEC validation. I have the doh-client running in docker using your dockerfile.client with pihole. Working well. I manage both via a docker-compose.yaml file.

Added pi-hole as potential dnssec validator

---

Readme.md

1. Enhanced documentation
- Formatting updates
- Language names added for code blocks
2. Added full guide link for Docker based setup in Guides section
3. Changed example code of Docker Swarm to Docker Compose.
4. IPV6 Support: Added notes for IPV6 support.
Docker Compose + IPV6 support needs a custom configuration file and it deserves to be a separate section that will include Docker compose configuration, OS level and Docker daemon changes. This is still under testing on multiple arch types (linux/amd64,linux/arm64,linux/arm/v7). IPV6 based Docker Compose is going to be a whole new guide as there are a lot configurations to be done.

Docker compose based doh-server setup example

---

.gitignore
doh-client/google.go

`doh-client/doh-client.conf`
```diff
diff --git a/doh-client/doh-client.conf b/doh-client/doh-client.conf
index b6eff00..b709830 100644
--- a/doh-client/doh-client.conf
+++ b/doh-client/doh-client.conf
@@ -1,9 +1,6 @@
listen = [
-    "127.0.0.1:53",
-    "127.0.0.1:5380",
-    "[::1]:53",
-    "[::1]:5380",
+    "127.0.0.1:1053",
@@ -25,8 +22,8 @@ upstream_selector = "random"
-[[upstream.upstream_ietf]]
-    url = "https://cloudflare-dns.com/dns-query"
+[[upstream.upstream_google]]
+    url = "https://dns.google/resolve"
weight = 50
@@ -131,4 +128,4 @@ no_ipv6 = false
no_user_agent = false
-verbose = false
+verbose = true
```
According to https://developers.google.com/speed/public-dns/docs/doh/json
> **do**
> boolean, default: `false`
>
> The DO (DNSSEC OK) flag. Use `do=1`, or `do=true` …

[JSON-DOH] Honor DNSSEC OK flag for incoming DNS requests

---

doh-client/doh-client.conf

Above, it was said that 8.8.8.8 had good ECS, so don't contradict that further down.
This confused a reviewer of https://github.com/NixOS/nixpkgs/pull/104530 :)

Fix an inconsistency in the example doh-client.conf

---

Readme.md

- Set traefik container version to 2.3 in docker-compose example. This supports recent lets encrypt changes.
- Remove docker swarm related references. Docker swarm example is no more valid. Docker compose is the best example available atm.

Documentation update: Docker example update

---

doh-server/ietf.go

Log for response patching only when verbose is enabled.
I have not touched SERVFAIL because those are not bad requests for clients, they are proper errors contacting upstream and other similar services do log them.

Log for response patching only when verbose is enabled

---

.github/workflows/go.yml
Makefile
go.mod

Add GitHub actions to build master and each PR.
I did not see a Makefile target to build for Windows, so I did not add the stanzas for that.
There are also no integration tests otherwise they could be added as well.
This PR additionally moves from Go 1.12 to Go 1.13 because of the modules support, which allows to not have a `deps` target anymore, since Go does that automatically. Build was failing without upgrading to Go 1.13

Add GitHub actions to build master and each PR

---

doh-server/google.go
doh-server/parse_test.go

Added missing tests for CIDR subnets parsing, adapted from #84, so that changes to the parsing logic can obey to the same tests.

fix: add unit tests for CIDR subnets parsing

---

Readme.md

Incorporating instructions from #104

docs: explain how to use DNS-over-TLS with nginx/STunnel

---

doh-server/ietf.go

Signed-off-by: Gontier Julien <gontierjulien68@gmail.com>
As talked here #136 now it the time too remove the Firefox 61-62 workaround patch before the next release.
There should be all of the patch gone, and i've test it in my branch for a long time with no issue to be seen.

Removing Firefox 61-62 workaround patch

---

.github/workflows/go.yml

Updated workflow to use ubuntu-latest as ubuntu-18.04 has been deprecated.

Update go.yml to use ubuntu-latest for runs-on

---

Makefile

As discussed in #151 , add the '-s -w' ldflags
Information on what those two ldflags does:
```
-s    disable symbol table
-w    disable DWARF generation
```

Add ldflags

---

doh-server/version.go

Pre-bump to next version 2.3.6
Ref: https://github.com/m13253/dns-over-https/commit/057797fed39d00577110cb0fcbea3f61dcabdd61#commitcomment-139691775

Pre-bump to next version 2.3.6

---

doh-client/version.go

Pre-bump doh-client to next version 2.3.6
Ref: https://github.com/m13253/dns-over-https/commit/057797fed39d00577110cb0fcbea3f61dcabdd61#commitcomment-139691775

Pre-bump doh-client to next version 2.3.6

---

Readme.md

Update example to use multiple upstream DNS servers
Ref: https://github.com/satishweb/docker-doh/pull/25

Update example to use multiple upstream DNS servers

---

systemd/doh-client.service
systemd/doh-server.service

This solves an issue that on (at least) Fedora and if NetworkManager starts too slow, systemd may stop trying to start it after hitting `StartLimitBurst` limit.
Thanks to systemd 254, by providing [`RestartSteps` and `RestartMaxDelaySec` options](https://www.man7.org/linux/man-pages/man5/systemd.service.5.html), we can let the service retry at an exponential backoff delay.
I choose the exponential factor to be 1.618, maxed at 76 seconds, because Fibonacci backoff seems to be another popular backoff sequence. By my educated guess, I think this should be a good number to start with?
I am not sure if this change would ruin somewhere else. Please cast your opinions before I merge it to the master branch.

When systemd service fail to start, use an exponential backoff delay to restart it
